/* Generated By:JJTree&JavaCC: Do not edit this line. Aula1Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Aula1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMECAPROGRAMA = 5;
  /** RegularExpression Id. */
  int ABREBLOCO = 6;
  /** RegularExpression Id. */
  int TERMINABLOCO = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int VARCHAR = 10;
  /** RegularExpression Id. */
  int SEPARAR = 11;
  /** RegularExpression Id. */
  int FIMINSTRUCAO = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int FOR = 16;
  /** RegularExpression Id. */
  int TO = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int IGUAL = 20;
  /** RegularExpression Id. */
  int SOMA = 21;
  /** RegularExpression Id. */
  int SUBTRACAO = 22;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 23;
  /** RegularExpression Id. */
  int DIVISAO = 24;
  /** RegularExpression Id. */
  int DECIMAL = 25;
  /** RegularExpression Id. */
  int NUMERICO = 26;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 27;
  /** RegularExpression Id. */
  int LETRA = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"chamada\"",
    "\"iniciosamba\"",
    "\"viradadedois\"",
    "\"int\"",
    "\"float\"",
    "\"varchar\"",
    "\",\"",
    "\"fechabossa\"",
    "\"mestre\"",
    "\"toque\"",
    "\"espere\"",
    "\"contagem\"",
    "\"parada\"",
    "\"bossa\"",
    "\"toquebossa\"",
    "\"=\"",
    "\" + \"",
    "\" - \"",
    "\" * \"",
    "\" / \"",
    "<DECIMAL>",
    "<NUMERICO>",
    "<IDENTIFICADOR>",
    "<LETRA>",
  };

}
