/* Generated By:JavaCC: Do not edit this line. Aula1TreeConstants.java Version 7.0.12 */
package parser;

public interface Aula1TreeConstants
{
  public int JJTMAIN = 0;
  public int JJTID = 1;
  public int JJTCOMECAPROGRAMA = 2;
  public int JJTABREBLOCO = 3;
  public int JJTTERMINABLOCO = 4;
  public int JJTCOMANDOS = 5;
  public int JJTDECLARARVARIAVEL = 6;
  public int JJTSEPARADOR = 7;
  public int JJTFIMINSTRUCAO = 8;
  public int JJTFUNCTION = 9;
  public int JJTIFSTATEMENT = 10;
  public int JJTCOND_IF = 11;
  public int JJTCOND_THEN = 12;
  public int JJTCOND_ELSE = 13;
  public int JJTFORSTATEMENT = 14;
  public int JJTREP_FOR = 15;
  public int JJTREP_TO = 16;
  public int JJTWHILESTATEMENT = 17;
  public int JJTREP_WHILE = 18;
  public int JJTREP_DO = 19;
  public int JJTTIPODADO = 20;
  public int JJTTIPO_INT = 21;
  public int JJTTIPO_FLOAT = 22;
  public int JJTTIPO_VARCHAR = 23;
  public int JJTATRIBUICAO = 24;
  public int JJTOP_MATEMATICA = 25;
  public int JJTTERMO = 26;
  public int JJTFATOR = 27;
  public int JJTCONTA = 28;
  public int JJTIGUAL = 29;
  public int JJTSOMA = 30;
  public int JJTSUBTRACAO = 31;
  public int JJTMULTIPLICACAO = 32;
  public int JJTDIVISAO = 33;
  public int JJTLETRA = 34;
  public int JJTDECIMAL = 35;
  public int JJTEXPRESSAO = 36;


  public String[] jjtNodeName = {
    "main",
    "ID",
    "comecaprograma",
    "abrebloco",
    "terminabloco",
    "comandos",
    "declararVariavel",
    "separador",
    "fiminstrucao",
    "function",
    "ifStatement",
    "cond_if",
    "cond_then",
    "cond_else",
    "forStatement",
    "rep_for",
    "rep_to",
    "whileStatement",
    "rep_while",
    "rep_do",
    "tipoDado",
    "tipo_int",
    "tipo_float",
    "tipo_varchar",
    "atribuicao",
    "op_matematica",
    "termo",
    "fator",
    "conta",
    "igual",
    "soma",
    "subtracao",
    "multiplicacao",
    "divisao",
    "letra",
    "decimal",
    "expressao",
  };
}
/* JavaCC - OriginalChecksum=92e1c5f36e113ae79ce3d07e03a4488e (do not edit this line) */
